/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DocumentLink: typeof import('./src/components/DocumentLink.vue')['default']
    HeroSlider: typeof import('./src/components/home/HeroSlider.vue')['default']
    HighlightCarousel: typeof import('./src/components/home/HighlightCarousel.vue')['default']
    IconifyIcon: typeof import('./src/components/IconifyIcon.vue')['default']
    PortfolioTable: typeof import('./src/components/software/PortfolioTable.vue')['default']
    SwiperCarousel: typeof import('./src/components/home/SwiperCarousel.vue')['default']
  }
}
